[package]
name = "jpush-rs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.63"
tokio = { version = "1", features = ["full"] }
